### ISSUE TITLE
Remove unnecessary packages from meta.yml ?

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openmmtools#103]
`openmmtools` has in the _run_ section in `meta.yml`
- `nose`
- `setuptools`

this causes unnecessary installation of these packages (I think) when using conda install.
I assume that just removing will break the tests in travis. So not sure what the best strategy is.
This is not really urgent.

**Comment by jchodera** [comment]
Take a look at how we do this for [`alchemy`](https://github.com/choderalab/alchemy/blob/master/devtools/conda-recipe/meta.yaml):
```yaml

package:
  name: alchemy-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm
    - numpy

  run:
    - python
    - openmm
    - numpy

test:
  requires:
    - nose
    - nose-timer
    - pymbar
    - openmmtools
    - click
    - netcdf4

  imports:
    - alchemy
```
The `test:` block has `requires:` that imports the various things needed only for testing, like `nose`.  This will install them in the conda `_test` environment and just make sure you can import the `alchemy` package.

In [`.travis.yml`](https://github.com/choderalab/alchemy/blob/master/.travis.yml), we then activate the `_test` environment and perform heavy-duty testing:
```yaml
script:
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe
  - source activate _test
  - conda install --yes --quiet nose nose-timer
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer && cd ..
```
You can also install the package you just built outside of the `_test` environment and make sure you can still run it even without those extra testing packages.
